# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install app dependencies
COPY package*.json ./

# Use npm ci to install dependencies without running scripts
RUN npm ci --ignore-scripts

# Copy all project files
COPY . .

# Build the project
RUN npm run build

# Set environment variables for Docker (actual values should be provided at runtime)
ENV YOUTUBE_API_KEY=""

# Command to run the MCP server
CMD ["node", "dist/index.js"]
